Repository AdamOswald/Huggingface-Space, pull requests merged in 2022-11, with the labels that each got.

#8 [Snyk] Security upgrade setuptools from 39.0.1 to 65.5.1
  requirements.txt
Labels: :mag: Ready for Review, No Changes

#11 Add files via upload
  test.py
Labels: :mag: Ready for Review, Extra Small

#13 Add .circleci/config.yml
  .circleci/config.yml
Labels: :mag: Ready for Review, Extra Small

#15 Add files via upload
  .github/workflows/codescan.yml
  .github/workflows/contrast-scan.yml
  .github/workflows/datree-validation.yml
  .github/workflows/docker-image.yml
  .github/workflows/docker-publish.yml
  .github/workflows/flawfinder.yml
  .github/workflows/g-snyk.yml
  .github/workflows/msvc.yml
  .github/workflows/neuralegion.yml
  .github/workflows/python-publish.yml
  .github/workflows/securitycodescan.yml
  .github/workflows/snyk-infrastructure.yml
  .github/workflows/snyk.yml
  .github/workflows/soos-dast-scan.yml
  .github/workflows/stackaid-dependency-generator.yml
  .github/workflows/supersnyk.yml
Labels: Extra Large

#18 Add files via upload
  requirements.txt
Labels: :mag: Ready for Review, No Changes
